FROM python:3.10

RUN mkdir /final_app

WORKDIR /final_app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN chmod a+x docker/*.sh

WORKDIR src

RUN alembic upgrade head

WORKDIR ..

RUN gunicorn dsh.app:server --bind=0.0.0.0:8050 --daemon

RUN gunicorn src.app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000
