"""Add models db

Revision ID: f074ba857f2b
Revises: 57092440e940
Create Date: 2023-03-09 15:03:24.395275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f074ba857f2b"
down_revision = "57092440e940"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_type", sa.String(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("models")
    # ### end Alembic commands ###
