"""Initial commit

Revision ID: 57092440e940
Revises: 
Create Date: 2023-03-07 11:14:12.469667

"""
from alembic import op
import sqlalchemy as sa
from src.core.settings import settings
from src.services.users import UsersService
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '57092440e940'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    users = op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('called_at', sa.DateTime(), nullable=True),
    sa.Column('called_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['called_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        users,
        [
            {
                'username': settings.admin_username,
                'password_hash': UsersService.hash_password(settings.admin_password),
                'created_at': datetime.now(),
                'role': 'admin',
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    op.drop_table('users')
    # ### end Alembic commands ###
